export interface NutritionItem {
  id: string;
  category: "fruits" | "meals" | "advice";
  categoryName: string;
  categoryNameEn?: string;
  title: string;
  titleEn?: string;
  subtitle: string;
  subtitleEn?: string;
  description: string;
  descriptionEn?: string;
  dietitianTip: string;
  dietitianTipEn?: string;
  badge: string;
  badgeColor: string;
  image: string;
  alt: string;
  benefits: string[];
  benefitsEn?: string[];
}

export const nutritionItems: NutritionItem[] = [
  {
    id: "fruits-berries",
    category: "fruits",
    categoryName: "তাজা ফলমূল",
    categoryNameEn: "Fresh Fruits",
    title: "অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ বেরি ও তাজা ফল",
    titleEn: "Antioxidant-Rich Berries & Fresh Fruits",
    subtitle: "রোগ প্রতিরোধ ক্ষমতা ও দীর্ঘায়ু",
    subtitleEn: "Immunity & Longevity",
    description: "স্ট্রবেরি, ব্লুবেরি ও জাম জাতীয় ফলে থাকে উচ্চমাত্রার ফ্ল্যাভোনয়েড ও অ্যান্থোসায়ানিন, যা কোষের অক্সিডেটিভ স্ট্রেস কমায়।",
    descriptionEn: "Strawberries, blueberries and berry-type fruits contain high levels of flavonoids and anthocyanins that reduce oxidative stress at the cellular level.",
    dietitianTip: "প্রতিদিনের নাশতায় একমুঠো তাজা বেরি বা দেশীয় আমলকী, পেয়ারা খেলে ত্বক তরুণ থাকে এবং রক্তচাপ নিয়ন্ত্রণে সহায়তা হয়।",
    dietitianTipEn: "A handful of fresh berries or local amla and guava with breakfast keeps your skin youthful and helps keep blood pressure in check.",
    badge: "ইমিউনিটি বুস্টার",
    badgeColor: "from-rose-500 to-red-600",
    image: "/nutrition/fruits-berries.jpg",
    alt: "রঙিন বেরি ও তাজা ফলমূল",
    benefits: ["রোগ প্রতিরোধ বৃদ্ধি", "ত্বক সতেজ রাখা", "ফ্রি-রেডিক্যাল প্রতিরোধ"],
    benefitsEn: ["Boosts immunity", "Keeps skin fresh", "Fights free radicals"],
  },
  {
    id: "meal-balanced-plate",
    category: "meals",
    categoryName: "ব্যালেন্সড খাবার",
    categoryNameEn: "Balanced Meals",
    title: "আদর্শ ব্যালেন্সড পুষ্টি প্লেট",
    titleEn: "The Ideal Balanced Nutrition Plate",
    subtitle: "ডায়াবেটিস ও ওজন নিয়ন্ত্রণে সেরা সমাধান",
    subtitleEn: "Best for Diabetes & Weight Control",
    description: "প্লেটের ৫০% রঙিন শাকসবজি, ২৫% চর্বিহীন প্রোটিন এবং ২৫% লাল চাল বা জটিল কার্বোহাইড্রেটে সাজানো আদর্শ খাদ্য থালা।",
    descriptionEn: "The ideal plate: 50% colourful vegetables, 25% lean protein, and 25% brown rice or complex carbohydrates.",
    dietitianTip: "খাবারের প্লেটে রঙের বৈচিত্র্য রাখুন। ব্যালেন্সড প্লেট মেথডে অতিরিক্ত ক্যালরি ছাড়াই পেট ভরা থাকে এবং মিষ্টির প্রতি আকর্ষণ কমে।",
    dietitianTipEn: "Add colour variety to your plate. The balanced plate method keeps you full without extra calories and reduces sugar cravings.",
    badge: "ব্যালেন্সড ডায়েট",
    badgeColor: "from-emerald-500 to-teal-600",
    image: "/nutrition/meal-balanced-plate.jpg",
    alt: "ব্যালেন্সড পুষ্টি প্লেট",
    benefits: ["রক্তে শর্করা নিয়ন্ত্রণ", "দীর্ঘস্থায়ী শক্তি", "ওজন ভারসাম্য"],
    benefitsEn: ["Blood sugar control", "Sustained energy", "Weight balance"],
  },
  {
    id: "advice-nutrition-plan",
    category: "advice",
    categoryName: "পুষ্টি পরামর্শ",
    categoryNameEn: "Nutrition Advice",
    title: "ব্যক্তিগত ক্যালরি ও খাদ্য পরিকল্পনা",
    titleEn: "Personalised Calorie & Diet Planning",
    subtitle: "ক্র্যাশ ডায়েট নয়, দীর্ঘমেয়াদী সুস্থতা",
    subtitleEn: "No crash diets — long-term wellness",
    description: "নিজের শারীরিক গঠন, বিএমআই ও রক্ত পরীক্ষার রিপোর্ট অনুযায়ী বিশেষজ্ঞের তত্ত্বাবধানে ডায়েট সাজানো জরুরি।",
    descriptionEn: "It is essential to design a diet under expert supervision based on your body composition, BMI and blood test reports.",
    dietitianTip: "অন্য কারো ডায়েট চার্ট অন্ধভাবে অনুসরণ করবেন না। আপনার শরীরের মেটাবলিজম অনুযায়ী পরিমাপিত পুষ্টিই আসল সুস্থতার চাবিকাঠি।",
    dietitianTipEn: "Never blindly follow someone else's diet chart. Nutrition calibrated to your body's own metabolism is the true key to health.",
    badge: "বিশেষজ্ঞ গাইডলাইন",
    badgeColor: "from-amber-500 to-orange-600",
    image: "/nutrition/advice-nutrition-plan.jpg",
    alt: "পুষ্টি পরিকল্পনা ও খাদ্য পরিমাপ",
    benefits: ["কাস্টমাইজড পুষ্টি চার্ট", "মেডিকেল নিউট্রিশন থেরাপি", "টেকসই জীবনধারা"],
    benefitsEn: ["Customised nutrition chart", "Medical nutrition therapy", "Sustainable lifestyle"],
  },
  {
    id: "fruits-citrus",
    category: "fruits",
    categoryName: "তাজা ফলমূল",
    categoryNameEn: "Fresh Fruits",
    title: "সাইট্রাস ফল ও প্রাকৃতিক ভিটামিন সি",
    titleEn: "Citrus Fruits & Natural Vitamin C",
    subtitle: "হজম প্রক্রিয়া ও মেটাবলিজম বৃদ্ধি",
    subtitleEn: "Improved Digestion & Metabolism",
    description: "কমলা, মাল্টা, বাতাবি লেবু ও পাতিলেবু প্রাকৃতিক ভিটামিন সি ও পেকটিন ফাইবারে ভরপুর, যা শরীর ডিটক্সিফাই করে।",
    descriptionEn: "Oranges, sweet lime, pomelo and lemons are rich in natural Vitamin C and pectin fibre, which help detoxify the body.",
    dietitianTip: "ভারী খাবারের পর এক টুকরো লেবু দিয়ে কুসুম গরম পানি হজমে সাহায্য করে ও আয়রন শোষণে সহায়তা করে।",
    dietitianTipEn: "A slice of lemon in warm water after a heavy meal aids digestion and improves iron absorption.",
    badge: "প্রাকৃতিক ডিটক্স",
    badgeColor: "from-amber-400 to-yellow-600",
    image: "/nutrition/fruits-citrus.jpg",
    alt: "তাজা সাইট্রাস ও লেবু জাতীয় ফল",
    benefits: ["ভিটামিন-সি সমৃদ্ধ", "হজম শক্তি বৃদ্ধি", "প্রাকৃতিক ডিটক্স"],
    benefitsEn: ["Rich in Vitamin C", "Improved digestion", "Natural detox"],
  },
  {
    id: "meal-salad-bowl",
    category: "meals",
    categoryName: "ব্যালেন্সড খাবার",
    categoryNameEn: "Balanced Meals",
    title: "হাই-ফাইবার রঙিন সালাদ বোল",
    titleEn: "High-Fibre Colourful Salad Bowl",
    subtitle: "অন্ত্রের স্বাস্থ্য ও কোলেস্টেরল নিয়ন্ত্রণ",
    subtitleEn: "Gut Health & Cholesterol Control",
    description: "শসা, টমেটো, লেটুস, কাঁচা বাদাম এবং উদ্ভিজ্জ সুপারফুডের সংমিশ্রণে তৈরি উচ্চ আঁশযুক্ত সালাদ।",
    descriptionEn: "A high-fibre salad made from cucumber, tomatoes, lettuce, raw nuts and plant-based superfoods.",
    dietitianTip: "মূল খাবারের ১০ মিনিট আগে এক বাটি ফ্রেশ সালাদ খেলে অতিরিক্ত খাবার গ্রহণ রোধ হয় এবং কোলেস্টেরল শোষণে বাধা দেয়।",
    dietitianTipEn: "Eating a bowl of fresh salad 10 minutes before the main meal prevents overeating and blocks cholesterol absorption.",
    badge: "গাট হেলথ",
    badgeColor: "from-green-500 to-emerald-600",
    image: "/nutrition/meal-salad-bowl.jpg",
    alt: "হাই-ফাইবার সালাদ বাটি",
    benefits: ["উচ্চ আঁশ ও ফাইবার", "কোলেস্টেরল হ্রাস", "অন্ত্র সুরক্ষা"],
    benefitsEn: ["High in fibre", "Lowers cholesterol", "Gut protection"],
  },
  {
    id: "advice-consultation",
    category: "advice",
    categoryName: "পুষ্টি পরামর্শ",
    categoryNameEn: "Nutrition Advice",
    title: "নিয়মিত ফলোআপ ও স্বাস্থ্য কাউন্সেলিং",
    titleEn: "Regular Follow-up & Health Counselling",
    subtitle: "PCOS, থাইরয়েড ও ফ্যাটি লিভার ব্যবস্থাপনা",
    subtitleEn: "PCOS, Thyroid & Fatty Liver Management",
    description: "রোগের সঠিক কারণ চিহ্নিত করে জীবনযাত্রার পরিবর্তন এবং খাদ্যভ্যাসে সুনির্দিষ্ট বৈজ্ঞানিক সমন্বয়।",
    descriptionEn: "Identifying the root cause of illness and implementing precise scientific adjustments to lifestyle and diet habits.",
    dietitianTip: "ওষুধের পাশাপাশি খাদ্য নিয়ন্ত্রণের মাধ্যমে ফ্যাটি লিভার ও হরমোনাল ভারসাম্য ৮০% পর্যন্ত স্বাভাবিক করা সম্ভব।",
    dietitianTipEn: "Alongside medication, dietary management can normalise fatty liver and hormonal balance by up to 80%.",
    badge: "ওয়ান-টু-ওয়ান কেয়ার",
    badgeColor: "from-teal-500 to-cyan-600",
    image: "/nutrition/advice-consultation.jpg",
    alt: "পুষ্টিবিদের ক্লিনিকাল কাউন্সেলিং",
    benefits: ["হরমোন ব্যালেন্স", "ফ্যাটি লিভার নিয়ন্ত্রণ", "নিয়মিত ট্র্যাকিং"],
    benefitsEn: ["Hormone balance", "Fatty liver control", "Regular tracking"],
  },
  {
    id: "fruits-variety",
    category: "fruits",
    categoryName: "তাজা ফলমূল",
    categoryNameEn: "Fresh Fruits",
    title: "মৌসুমি ফলের রংধনু পুষ্টি",
    titleEn: "Rainbow Nutrition from Seasonal Fruits",
    subtitle: "প্রতিটি রঙে লুকিয়ে আছে বিশেষ পুষ্টিগুণ",
    subtitleEn: "Each colour holds unique nutrients",
    description: "লাল, হলুদ, সবুজ ও বেগুনী ফলমূল শরীরের বিভিন্ন অঙ্গের কোষকে পুনরুজ্জীবিত করতে বিশেষ ভূমিকা রাখে।",
    descriptionEn: "Red, yellow, green and purple fruits each play a unique role in regenerating cells of different organs in the body.",
    dietitianTip: "জুস না বানিয়ে সবসময় গোটা ফল চিবিয়ে খান। এতে ফলের প্রাকৃতিক আঁশ অটুট থাকে এবং সুগার স্পাইক হয় না।",
    dietitianTipEn: "Always chew whole fruits instead of juicing them. This keeps the natural fibre intact and prevents sugar spikes.",
    badge: "মৌসুমি পুষ্টি",
    badgeColor: "from-purple-500 to-indigo-600",
    image: "/nutrition/fruits-variety.jpg",
    alt: "নানা রঙের তাজা ফলের সমাহার",
    benefits: ["প্রাকৃতিক সুগার", "ফাইটোনিউট্রিয়েন্ট", "সুস্থ হৃদযন্ত্র"],
    benefitsEn: ["Natural sugars", "Phytonutrients", "Healthy heart"],
  },
  {
    id: "meal-healthy-dish",
    category: "meals",
    categoryName: "ব্যালেন্সড খাবার",
    categoryNameEn: "Balanced Meals",
    title: "হার্ট ফ্রেন্ডলি মেডিটেরেনিয়ান মিল",
    titleEn: "Heart-Friendly Mediterranean Meal",
    subtitle: "স্বাস্থ্যকর ফ্যাট ও অলিভ অয়েলের সমন্বয়",
    subtitleEn: "Healthy Fats & Olive Oil Harmony",
    description: "ওমেগা-৩ ফ্যাটি অ্যাসিড, উদ্ভিজ্জ প্রোটিন এবং তাজা শাকসবজি দিয়ে রান্না করা হার্ট বান্ধব পুষ্টিকর খাদ্য।",
    descriptionEn: "A heart-friendly nutritious meal cooked with omega-3 fatty acids, plant protein and fresh vegetables.",
    dietitianTip: "অতিরিক্ত ডালডা বা পোড়া তেলের বদলে কোল্ড প্রেসড তেল এবং পর্যাপ্ত বীজ (চিয়া সিড, তিসি) রাখুন।",
    dietitianTipEn: "Replace excess hydrogenated fat or burnt oil with cold-pressed oils and adequate seeds (chia, flaxseed).",
    badge: "কার্ডিও প্রটেক্ট",
    badgeColor: "from-blue-500 to-emerald-600",
    image: "/nutrition/meal-healthy-dish.jpg",
    alt: "স্বাস্থ্যকর মেডিটেরেনিয়ান খাবার",
    benefits: ["ওমেগা-৩ ও ভালো ফ্যাট", "হার্ট সুরক্ষা", "উচ্চ পুষ্টিমান"],
    benefitsEn: ["Omega-3 & healthy fats", "Heart protection", "High nutritional value"],
  },
  {
    id: "advice-healthy-lifestyle",
    category: "advice",
    categoryName: "পুষ্টি পরামর্শ",
    categoryNameEn: "Nutrition Advice",
    title: "পর্যাপ্ত হাইড্রেশন ও সুস্থ লাইফস্টাইল",
    titleEn: "Adequate Hydration & Healthy Lifestyle",
    subtitle: "ডিটক্সিফিকেশন ও কিডনি সুরক্ষা",
    subtitleEn: "Detoxification & Kidney Protection",
    description: "প্রতিদিন পর্যাপ্ত পানি পান, সময়মত বিশ্রাম এবং চাপমুক্ত জীবনযাপন সঠিক পুষ্টির কার্যকারিতা বহুগুণ বাড়িয়ে দেয়।",
    descriptionEn: "Drinking adequate water daily, resting on time and stress-free living multiplies the effectiveness of proper nutrition.",
    dietitianTip: "দিনে অন্তত ২.৫ থেকে ৩ লিটার পানি পান করুন। ক্ষতিকর কোমল পানীয় ও প্রসেসড জুস সম্পূর্ণরূপে এড়িয়ে চলুন।",
    dietitianTipEn: "Drink at least 2.5 to 3 litres of water a day. Completely avoid harmful soft drinks and processed juices.",
    badge: "সুস্থ অভ্যাস",
    badgeColor: "from-sky-500 to-blue-600",
    image: "/nutrition/advice-healthy-lifestyle.jpg",
    alt: "হাইড্রেটিং পানি ও স্বাস্থ্যকর খাবার",
    benefits: ["কিডনি সুরক্ষা", "টক্সিন দূরীকরণ", "মানসিক শক্তি"],
    benefitsEn: ["Kidney protection", "Toxin elimination", "Mental energy"],
  },
];
